// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iozehxhgnzspxfiqpsvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvemVoeGhnbnpzcHhmaXFwc3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4OTI5NTEsImV4cCI6MjA1MTQ2ODk1MX0.A7eLEXtKW79pTiMj12knrjwyJAGacyumiwGM3Yi8Jis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);